### ISSUE TITLE
rest_cookie_invalid_nonce error

### ISSUE THREAD

**Issue by drewbaker** [MikhailRoot/samesite-cookie-manager#1]
Firstly, I love this plugin! Really helps us with headless WordPress.

We use this with a bunch of WP-GraphQL plugins. And today in Chrome we noticed that they all stopped working if we have this plugin enabled.

A REST API failing...
![Screen Shot 2021-12-01 at 2 50 23 PM](https://user-images.githubusercontent.com/475015/144327956-a70a8992-718c-4e50-9034-baba138e7d4b.png)

Cookies that show on login with plugin enabled:
![Screen Shot 2021-12-01 at 2 49 58 PM](https://user-images.githubusercontent.com/475015/144327982-2dc68572-7d59-434a-85c4-cce6c41e0c5d.png)

Cookies that show when plugin is disabled:
![Screen Shot 2021-12-01 at 2 49 23 PM](https://user-images.githubusercontent.com/475015/144328065-7b31ddd5-3ce2-4118-b7f3-7a92aeab9157.png)

I'm not sure what's going on here, and if it's something that needs to be fixed in WP-GQL or this plugin.

**Comment by rsm0128** [comment]
@drewbaker 
It seems like you have the issue because you have `http://` instead of `https://` for your 'home' option.
Please check `get_option('home')` or `hom_url()` for your site and ensure if it is `https`
